-- if vim.g.neovide then
--     require("smear_cursor").setup({
--         -- opts = {                                -- Default  Range
--         --     cursor_color = 
--         --     stiffness = 0.8,                      -- 0.6      [0, 1]
--         --     trailing_stiffness = 0.5,             -- 0.4      [0, 1]
--         --     stiffness_insert_mode = 0.7,          -- 0.5      [0, 1]
--         --     trailing_stiffness_insert_mode = 0.7, -- 0.5      [0, 1]
--         --     damping = 0.8,                        -- 0.65     [0, 1]
--         --     damping_insert_mode = 0.8,            -- 0.7      [0, 1]
--         --     distance_stop_animating = 0.5,        -- 0.1      > 0
--         --     time_interval = 7, -- milliseconds
--         -- },
--         opts = {
--             cursor_color = "#ff8800",
--             stiffness = 0.3,
--             trailing_stiffness = 0.1,
--             damping = 0.5,
--             trailing_exponent = 5,
--             never_draw_over_target = true,
--             hide_target_hack = true,
--             gamma = 1,
--             time_interval = 7, -- milliseconds
--         }
--     })
-- end
